add feature to replace jar after execution
mogproject/javactl pull request #25
Opened 2016-12-15 10:29 UTC by ocadaruma

Add `staging-jar` setting to deploy new jar while app is running.
This feature works as follows:

- If  both`app.jar` and `app.staging_jar` are set, replace jar file at `app.jar` with `app.staging_jar` after execution.

Motivation:

- Imagine that you run java-batch application via javactl.
- If you deploy new jar to `app.jar`, JVM class loader fails to invoke methods in unloaded classes.

2016-12-22 05:12 UTC, mogproject requested changes

2016-12-22 05:12 UTC, mogproject commented on src/javactl/executor/executor.py
> +    def _replace_jar(self):
I think this is necessary. (Do nothing when failed)
```
 if self.failed:
    return self
```

2016-12-22 05:12 UTC, mogproject commented on src/javactl/executor/executor.py
> +        if jar is not None and staging_jar is not None:
You should implement "dry-run" mode.

2016-12-22 05:14 UTC, mogproject commented
This task should be done by an external shell script and "post commands" option. Is there any reason why you do not want to use "post commands"?

2017-01-16 06:49 UTC, ocadaruma commented
@mogproject Got it.

2017-01-16 06:49 UTC, closed without merging